---
version: '3'
services:
  ghost:
    image: ghost:1-alpine
    ports:
    - 6677:2368
  mydb:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: intelliq
    links:
      ghost:my.ghost
...